#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6748661236                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                     # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/id6748661236                                        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : QR & Barcode Scanner Pro — fast, free, offline, and lightweight. Scan QR codes & barcodes instantly, open links, view history, and create your own QR codes. No ads!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Leandro Berli                                
your_link                                 : https://leandroberli.com                     
your_city                                 : Barcelona                                
email_address                             : leandroberli@gmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : leandroberli
twitter_username                          : 
github_username                           : leandroberli
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Scan QR & Barcodes super fast!
    description                           : Scan any QR code or barcode instantly. Whether it’s a product label, a website URL, or contact info.
    fontawesome_icon_name                 : qrcode

  - title                                 : Create Custom QR Codes
    description                           : Generate your own QR codes with custom text, URLs, and colors.
    fontawesome_icon_name                 : qrcode

  - title                                 : View Scan History
    description                           : Keep track of all your scans with a built-in history feature.
    fontawesome_icon_name                 : history

  - title                                 : Offline Functionality
    description                           : Scan and create QR codes without an internet connection.
    fontawesome_icon_name                 : plane

  - title                                 : Read QR from image or gallery
    description                           : Use your device's camera or photo library to scan QR codes from images.
    fontawesome_icon_name                 : image

  - title                                 : Share & Export
    description                           : Easily share your scanned data via email, social media, or messaging apps.
    fontawesome_icon_name                 : share

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#35AF5A"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


#"#35AF5A") ?? .black
# static let customGreen2: UIColor = UIColor(hex:"#277656"











####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
